---
driver:
  name: vagrant
  synced_folders:
      - ['test', '/backups', 'create: true', owner: "root", group: "root"]
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 13.8.5

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    provisioner:
      policyfile: policyfiles/default.rb
    verifier:
      inspec_tests:
        - test/integration/default
  - name: restore
    provisioner:
      policyfile: policyfiles/restore.rb
    attributes:
      mcs:
        restore:
          file: '/backups/chef-server-backup-201810300340.tgz'
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/legacy
        - test/integration/policyfiles
  - name: backup
    provisioner:
      policyfile: policyfiles/backup.rb
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/backup
  - name: cron
    provisioner:
      policyfile: policyfiles/cron.rb
    attributes:
      mcs:
        cron:
          policyfile_archive: '/backups/policyfiles/base-53e07f37074575abfe75bbb74032f6cd63fc566ff2b8e655f9a2ddf91a3615a8.tgz'
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/cron
  - name: legacy
    provisioner:
      policyfile: policyfiles/legacy.rb
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/legacy
  - name: policyfile
    provisioner:
      policyfile: policyfiles/policyfile.rb
    attributes:
      mcs:
        policyfile:
          dir: '/backups/policyfiles'
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/policyfiles
  - name: everything
    provisioner:
      policyfile: policyfiles/everything.rb
    attributes:
      mcs:
        cookbooks:
          dir: '/backups/cookbooks'
        environments:
          dir: '/backups/environments'
        roles:
          dir: '/backups/roles'
        policyfile:
          dir: '/backups/policyfiles'
        restore:
          file: '/backups/chef-server-backup-201810300340.tgz'
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/backup
        - test/integration/legacy
        - test/integration/policyfiles
