---
driver:
  name: vagrant
  synced_folders:
      - ['test', '/backups', 'create: true', owner: "root", group: "root"]
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 13.8.5

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    provisioner:
      policyfile: policyfiles/default.rb
    verifier:
      inspec_tests:
        - test/integration/default
  - name: restore
    provisioner:
      policyfile: policyfiles/default.rb
    attributes:
      mcs:
        policyfile:
          dir: '/backups'
        restore:
          file: '/backups/chef-server-backup-201809030650.tgz'
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/policyfiles
  - name: backup
    provisioner:
      policyfile: policyfiles/backup.rb
    verifier:
      inspec_tests:
        - test/integration/default
  - name: cron
    provisioner:
      policyfile: policyfiles/cron.rb
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/cron
  - name: policyfile
    provisioner:
      policyfile: policyfiles/policyfile.rb
    attributes:
      mcs:
        policyfile:
          dir: '/backups'
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/policyfiles
  - name: everything
    provisioner:
      policyfile: policyfiles/everything.rb
    attributes:
      mcs:
        policyfile:
          dir: '/backups'
        restore:
          file: '/backups/chef-server-backup-201809030650.tgz'
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/policyfiles
